// Generated by CoffeeScript 1.6.2
(function() {
  var attrs, coffee, coffees, end, loc, location, new_locations, params, range, search_locations, start, store_locations, to_print, _i, _j, _k, _l, _len, _len1, _len2, _results,
    __slice = [].slice;

  alert('Ranges');

  range.slice(1, 5);

  range.slice(1, 4);

  start = 5;

  end = 10;

  range = (function() {
    _results = [];
    for (var _i = start; start <= end ? _i <= end : _i >= end; start <= end ? _i++ : _i--){ _results.push(_i); }
    return _results;
  }).apply(this);

  range.slice(1, 5);

  range.slice(1, +range.length + 1 || 9e9);

  range.slice(1);

  alert('Arrays');

  store_locations = ['Orlando', 'Winter Park', 'Sanford'];

  alert('Loops');

  for (_j = 0, _len = store_locations.length; _j < _len; _j++) {
    location = store_locations[_j];
    alert("Location: " + location);
  }

  alert('List comprehensions');

  for (_k = 0, _len1 = store_locations.length; _k < _len1; _k++) {
    location = store_locations[_k];
    alert("Location: " + location);
  }

  store_locations = (function() {
    var _l, _len2, _results1;

    _results1 = [];
    for (_l = 0, _len2 = store_locations.length; _l < _len2; _l++) {
      loc = store_locations[_l];
      _results1.push("" + loc + ", FL");
    }
    return _results1;
  })();

  for (_l = 0, _len2 = store_locations.length; _l < _len2; _l++) {
    loc = store_locations[_l];
    if (loc !== 'Sanford') {
      geolocate(loc);
    }
  }

  new_locations = (function() {
    var _len3, _m, _results1;

    _results1 = [];
    for (_m = 0, _len3 = store_locations.length; _m < _len3; _m++) {
      loc = store_locations[_m];
      if (loc !== 'Sanford') {
        _results1.push(loc);
      }
    }
    return _results1;
  })();

  alert('Splats for a variable number of arguments');

  search_locations = function() {
    var brand, cities;

    brand = arguments[0], cities = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return "looking for " + brand + " in " + (cities.join(', '));
  };

  search_locations('Starbucks', 'Orlando', 'Winter Park');

  params = ['Starbucks', 'Orlando', 'Winter Park'];

  search_locations.apply(null, params);

  alert('Objects');

  coffee = {
    name: 'French',
    strength: 1,
    brew: function() {
      return alert("brewing " + this.name);
    },
    pour: function(amount) {
      if (amount == null) {
        amount = 1;
      }
      if (amount === 1) {
        return 'Poured a single cup';
      } else {
        return "Poured " + amount + " cups";
      }
    }
  };

  coffee.brew();

  coffees = {
    french: {
      strength: 1,
      in_stock: 20
    },
    italian: {
      strength: 2,
      in_stock: 40
    },
    decaf: {
      strength: 4,
      in_stock: 50
    }
  };

  for (coffee in coffees) {
    attrs = coffees[coffee];
    "" + coffee + " has " + attrs.in_stock;
  }

  to_print = (function() {
    var _results1;

    _results1 = [];
    for (coffee in coffee) {
      attrs = coffee[coffee];
      if (attrs.in_stock > 0) {
        _results1.push("" + coffee + " has " + attrs.in_stock);
      }
    }
    return _results1;
  })();

  to_print.join(', ');

}).call(this);
