// Generated by CoffeeScript 1.6.2
(function() {
  var Coffee, MaxgoodHouse, boring, french,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Coffee = (function() {
    function Coffee(name, strength) {
      this.name = name;
      this.strength = strength != null ? strength : 1;
    }

    Coffee.prototype.brew = function() {
      return alert("brewing " + this.name);
    };

    Coffee.prototype.pour = function(amount) {
      if (amount == null) {
        amount = 1;
      }
      if (amount === 1) {
        return "Poured a single cup";
      } else {
        return "Poured " + amount + " cups";
      }
    };

    return Coffee;

  })();

  french = new Coffee("French", 2);

  french.brew();

  MaxgoodHouse = (function(_super) {
    __extends(MaxgoodHouse, _super);

    function MaxgoodHouse(name, strength) {
      this.name = name;
      this.strength = strength != null ? strength : 0;
      this.brand = "Maxgood House";
    }

    MaxgoodHouse.prototype.brew = function() {
      return alert("Brewing " + this.brand + " " + this.name);
    };

    MaxgoodHouse.prototype.pour = function(amount) {
      if (amount == null) {
        amount = 1;
      }
      return "" + (MaxgoodHouse.__super__.pour.call(this, amount)) + ", but it sucks";
    };

    return MaxgoodHouse;

  })(Coffee);

  boring = new MaxgoodHouse("Boring");

  boring.brew();

  boring.pour();

}).call(this);
