// Generated by CoffeeScript 1.6.2
(function() {
  var cupsOfCoffee, message;

  alert("'true yes on' translate to 'true'; 'false no off' translate to 'false'; '== is' translate to '===' ; '!= isnt' translate to '!==' ");

  if (age < 18) {
    alert('Under age');
  } else {
    alert('of age');
  }

  if (has_money) {
    alert('Welcome !');
  } else {
    alert('Piss off !');
  }

  if (paid() && coffee() === true) {
    pour();
  }

  if (!Decaf()) {
    addCaffeine();
  }

  if (!Decaf()) {
    addCaffeine();
  }

  alert('Chained Comparisons');

  if ((2 < new_level && new_level < 5)) {
    alert('In range !');
  }

  alert('Switch statements');

  message = (function() {
    switch (cupsOfCoffee) {
      case 0:
        return 'Asleep';
      case 1:
        return 'Eyes open';
      case 2:
        return 'Buzzled';
      default:
        return 'Dangerous';
    }
  })();

  alert('Existential Operators');

  cupsOfCoffee = 5;

  if (cupsOfCoffee != null) {
    alert("No more typeof=='undefined' and 'null' ");
  }

  alert('Set cupsOfCoffee to zero unless previously set');

  if (cupsOfCoffee == null) {
    cupsOfCoffee = 0;
  }

  alert('Call brew() on coffeePot only if it exists. Do not overuse it !');

  if (typeof coffeePot !== "undefined" && coffeePot !== null) {
    coffeePot.brew();
  }

}).call(this);
